### ISSUE TITLE
Release libcamera 0.2.3 to include unreleased fixes

### ISSUE THREAD

**Issue by frederikstroem** [lit-robotics/libcamera-rs#33]
I am experiencing issue #29 on my Raspberry Pi when importing libcamera "0.2.2" into my Cargo.toml; only cloning the Git repo seems to work, as #30 has not been released on Crates.io as far as I can tell.

P.S. Thank you for open-sourcing this wonderful project! ❤️ It's really useful for my master's thesis.

**EDIT:** I found that adding the Git source repository as a dependency serves as a temporary workaround, e.g.:
```toml
[dependencies]
drm-fourcc = "2.2"
image = "0.24.7"
libcamera = { git = "https://github.com/lit-robotics/libcamera-rs.git" }
```
